### ISSUE TITLE
Slash Command support

### ISSUE THREAD

**Issue by aqali1** [Kaktushose/jda-commands#31]
Would be nice if commands made had the slash auto complete support.

**Comment by Kaktushose** [comment]
I already made up some thoughts about  implementing slash commands and buttons, but I haven't found the time to start working on it yet.

**Comment by Kaktushose** [comment]
Update: 

With version 2.0.0 finally being released, I've created the foundation for supporting slash commands as well. This was important for me, because v1 was just a PoC I didn't want to overextend. 

Since JDA5 is still in alpha, I will not start working on it for now, because JDA4 will deprecate soon, but JDA5 isn't production ready yet. 

When JDA5 beta arrives, I'll start working on this feature.

**Comment by Kaktushose** [comment]
Update:

I've started working on interactions. See [dev-jda5](https://github.com/Kaktushose/jda-commands/tree/dev-jda5) and the [project board](https://github.com/Kaktushose/jda-commands/projects/4) for details.

**Comment by Kaktushose** [comment]
Update:

This feature is now available in [`v2.3.0-alpha.1`](https://github.com/Kaktushose/jda-commands/releases/tag/v2.3.0-alpha.1)
